name: Build Resource Pack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create ZIP of resource pack
      run: |
        mkdir build
        zip -r build/CustomStoreUI.zip assets pack.mcmeta

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v3
      with:
        name: CustomStoreUI
        path: build/CustomStoreUI.zip
